### ISSUE TITLE
Issue : 전역적 상태관리

### ISSUE THREAD

**Issue by himchan94** [OllaEdu-Wangong-Sherpa/OllaEdu-Wangong-Sherpa#31]
## Problem & Opportunity
**먼저 성적 현황 페이지를 구현하면서 데이터를 받아오는 로직 및 로그인 여부 체크를 하기위한 상태관리 및 비동기 통신 부분을 논의없이 독단적으로 구현한 점 사과드립니다 🙇🙇**

이 이슈 로그를 통해서 전역적 상태관리를 위해 ContextAPI와 커스텀 useReducer 훅을 사용한 선택한 이유를 공유드리고, 팀원님들의 피드백을 받으려고 합니다.

먼저, 전역적 상태관리가 필요한 두 가지 이유부터 설명 드리겠습니다. 

1) 로그인 여부를 전역적으로 관리하고 있어야, 페이지 내의 하위 컴포넌트에서 로그아웃 버튼 클릭 시, 관리되고 있는 로그인 상태를 리셋하고, 이와 동시에 다시 로그인 페이지로 이동하는 동작을 prop drilling 없이 간단하게 구현할 수 있습니다.

2)  API를 통해 받아온 데이터에서, 사용자 이름, 직군, 성적 등을 각각의 페이지에서 사용하고 있습니다. 이 또한 전역적 상태관리를 사용하면, prop drilling 없이 간단하게 구현할 수 있습니다.

위 이유로 전역적 상태관리가 필요하며, 저는 3가지 방식을 고려했습니다.
  
### 1. Redux +  redux-thunk or redux-saga..
제일 먼저, 강의에서 배웠던 Redux와 미들웨어를 통한 비동기 통신 및 전역적 상태관리를 고려했습니다.

#### 선택하지 않은 이유 : 가벼운 로그인 API와 성적현황 API

현재 기업에서 제공받은 로그인 API는 아래와 같이 고정된 API 키를 활용해서 헤더에 아이디와, 패스워드를 실어보내면
별도의 토큰없이 success 와 fail 메세지만 받고 있습니다.

```.js
   fetch("https://kimcodi.kr/external_api/report/login.php", {
      method: "POST",
      body: JSON.stringify({
        api_key: "api 키",
        user_id: "fastcampus3",
        user_pw: "1234"
      })
    })
```

성적현황 API도 별도의 토큰없이 아래처럼, 고정된 유저 ID가 있는 query문을 통해 데이터를 받아옵니다.

```js
    const getData = fetch(
      "https://kimcodi.kr/external_api/report/resultSearch.php?%20mem_id=0909ok***"
    )
      .then((res) => res.json())
      .then((data) => {
        console.log(data);
      });
```

**위의 두 가지 경우외엔 별도의 비동기 로직이 필요 없습니다.**

단 두 가지의 비동기 로직과 그 결과의 상태관리를 위해 무거운 Redux와 미들웨어 라이브러리를 설치하는 것은 비효율적이라고 생각했고, 선택하지 않았습니다.
  
### 2. React Query

요즘 배민의 주문 페이지에서 사용하고 있는 서버 상태관리 라이브러리인데, 

컴포넌트 내의 서버 데이터를 fetching, caching, synchronizing and updating 하기 쉽게 만들어준다고 합니다. 
https://react-query.tanstack.com/ (React Query 공식문서)

React-Query와 ContextAPI를 함께 사용하면, 전역적인 상태관리가 가능하며 아래와 같이 데이터 통신 후 
isLoading, isError, data, error 값들을 자동으로 반환하여, 비동기 데이터 통신 및 상태관리를 쉽게 만들어줍니다.

또한 추가 config 객체를 통해 데이터 요청 실패 시 어떤 처리를 할 지, 받아온 데이터를 가공 등등 다양한 로직을 실행할 수 있습니다.

```js
function Todos() {
   const { isLoading, isError, data, error } = useQuery('todos', fetchTodoList)
 
   if (isLoading) {
     return <span>Loading...</span>
   }
 
   if (isError) {
     return <span>Error: {error.message}</span>
   }
 
   // We can assume by this point that `isSuccess === true`
   return (
     <ul>
       {data.map(todo => (
         <li key={todo.id}>{todo.title}</li>
       ))}
     </ul>
   )
 }
```

### 3 ContextAPI + useReducer

ContextAPI + useReducer를 사용하는 방법을 고민했습니다.
아래 그림처럼 컴포넌트 내에서 contextAPI를 통해 전역적으로 공유되고 있는 useReducer의 dispatch를 통해 컴포넌트 어디서는 전역적 상태를 업데이트 할 수 있습니다.

![image](https://user-images.githubusercontent.com/71649055/156918658-1b2c03e9-1a5f-4b30-a91a-86485f2a792b.png)

하지만 이 방법도 문제가 있었는데, 컴포넌트 내에서 비동기 통신을 실행하고 데이터를 받아올 때, 로그인 API를 통해 받아오는 간단한 데이터는 괜찮지만, 정돈되지 않은 형태로 받아지는 다수의 성적현황 데이터 같은 경우는 데이터 정제과정이 필요하는 부분이었습니다.

그래서 **"컴포넌트 내에는 최소한의 state만 존재하고, View를 나타내는 부분만 있는 것이 프로젝트의 유지-보수를 쉽게 해주지 않을까?"  하는 생각이 들었고, 비동기 통신과 데이터 정제 로직을 밖으로 빼는 방법을 고민했습니다.**

### 4. ContextAPI + **커스텀 useReducer**

3번의 ContextAPI와 useReducer 방식에서, 비동기 통신과 데이터 정제 로직을 밖으로 빼기 위하여 커스텀 useReducer 혹을 만들었습니다.

![image](https://user-images.githubusercontent.com/71649055/156919456-6891e9d1-452e-40a7-9013-f66b21b47ced.png)

redux-thunk 미들웨어에서 아이디어를 얻었고, custom useReducer를 통해 dispatch를 할 때 단순히 {type: ??, payload: ??} 형태의 객체가 아니라 함수 타입의 액션을 받으면, 해당 함수를 실행하고 dispatch를 할 수 있도록 만들었습니다.

아래는 useMwReducer라는 custom hook이며, useReducer를 골조로 만들었고, 
만약 dispatch 되는 액션의 타입이 함수라면, 그 함수를 실행할 수 있도록 만들었습니다.

```js
const useMwReducer = (reducer, initialState) => {
  const [state, dispatch] = useReducer(reducer, initialState);

  const dispatchWithMiddleware = action => {
    if (typeof action === "function") {
      return action(dispatch, state);
    }

    dispatch(action);
  };

  return [state, dispatchWithMiddleware];
};
```

```js
export const loadData = () => async (dispatch, state) => {
  dispatch(setLoading(true));
  const data = await fetch(
    "https://kimcodi.kr/external_api/report/resultSearch.php?%20mem_id=0909ok***"
  )
    .then(res => res.json())
    .then(data => data.result);

... 데이터 정제 로직
};

```

## Ref
https://techblog.woowahan.com/6339/ (배민 React Query 기술 블로그)
https://www.youtube.com/watch?v=MArE6Hy371c (배민 React Query 테크 세미나)
https://github.com/reduxjs/redux-thunk (리덕스 thunk)

**Comment by zi-gae** [comment]
의견 잘 읽어보았습니다. ㅎㅎ 좋은 식견이고 한번쯤 고민 해볼만한 주제이기도 합니다. 서로 인사이트 받을 수 있도록 팀미팅 때 한번 더 리마인드 되면 좋을 것 같네요.

다른 이야기이지만 예제코드의 키 값이 공개 되어 있는데 유효한 키라면 가리셔야 할 것 같습니다

**Comment by himchan94** [comment]
앗, 실수로 멘토님께도 이슈 공유드렸네요!! 죄송합니다 ㅠㅠ
api키는 바로 가렸습니다. 감사합니다!!!
